/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

package net.projeceuler;

public class EvenFibonacciNumbers {

    public static void main(String[] args) {
        int maxValue = 4000000;
        int fibboMaxValue = sumValuesUnderDeclared(maxValue);

        System.out.println("Suma wszystkich wyrazow ciagu podzielnych przez 2 i mniejszych niz " + maxValue + " wynosi " + fibboMaxValue);

    }

    private static int sumValuesUnderDeclared(int MaxValue) {

        int[] ArrayValues = new int[3];
        ArrayValues[0] = 1;
        ArrayValues[1] = 1;
        ArrayValues[2] = 0;
        int sum = 0;

        while (ArrayValues[2] < MaxValue) {
            ArrayValues[2] = ArrayValues[0] + ArrayValues[1];

            if (ArrayValues[2] % 2 == 0) {
                sum += ArrayValues[2];
            }

            ArrayValues[0] = ArrayValues[1];
            ArrayValues[1] = ArrayValues[2];
        }

        return sum;
    }

}
